services:
  - type: web
    name: inventory-order-api
    env: docker
    plan: free
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-order-db
          property: connectionString

databases:
  - name: inventory-order-db
    plan: free
